In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
df=pd.read_excel('Netflix Dataset Latest 2021.xlsx')

In [3]:
df

,Title,Genre,Tags,Languages,Series or Movie,Hidden Gem Score,Country Availability,Runtime,Director,Writer,...,Netflix Release Date,Production House,Netflix Link,IMDb Link,Summary,IMDb Votes,Image,Poster,TMDb Trailer,Trailer Site
0,Lets Fight Ghost,"Crime, Drama, Fantasy, Horror, Romance","Comedy Programmes,Romantic TV Comedies,Horror ...","Swedish, Spanish",Series,4.3,Thailand,< 30 minutes,Tomas Alfredson,John Ajvide Lindqvist,...,2021-03-04,"Canal+, Sandrew Metronome",https://www.netflix.com/watch/81415947,https://www.imdb.com/title/tt1139797,A med student with a supernatural gift tries t...,205926.0,https://occ-0-4708-64.1.nflxso.net/dnm/api/v6/...,https://m.media-amazon.com/images/M/MV5BOWM4NT...,https://www.youtube.com/watch?v=LqB6XJix-dM,YouTube
1,HOW TO BUILD A GIRL,Comedy,"Dramas,Comedies,Films Based on Books,British",English,Movie,7.0,Canada,1-2 hour,Coky Giedroyc,Caitlin Moran,...,2021-03-04,"Film 4, Monumental Pictures, Lionsgate",https://www.netflix.com/watch/81041267,https://www.imdb.com/title/tt4193072,"When nerdy Johanna moves to London, things get...",2838.0,https://occ-0-1081-999.1.nflxso.net/dnm/api/v6...,https://m.media-amazon.com/images/M/MV5BZGUyN2...,https://www.youtube.com/watch?v=eIbcxPy4okQ,YouTube
2,The Con-Heartist,"Comedy, Romance","Romantic Comedies,Comedies,Romantic Films,Thai...",Thai,Movie,8.6,Thailand,> 2 hrs,Mez Tharatorn,"Pattaranad Bhiboonsawade, Mez Tharatorn, Thods...",...,2021-03-03,NaN,https://www.netflix.com/watch/81306155,https://www.imdb.com/title/tt13393728,After her ex-boyfriend cons her out of a large...,131.0,https://occ-0-2188-64.1.nflxso.net/dnm/api/v6/...,https://m.media-amazon.com/images/M/MV5BODAzOG...,https://www.youtube.com/watch?v=md3CmFLGK6Y,YouTube
3,Gleboka woda,Drama,"TV Dramas,Polish TV Shows,Social Issue TV Dramas",Polish,Series,8.7,Poland,< 30 minutes,NaN,NaN,...,2021-03-03,NaN,https://www.netflix.com/watch/81307527,https://www.imdb.com/title/tt2300049,A group of social welfare workers led by their...,47.0,https://occ-0-2508-2706.1.nflxso.net/dnm/api/v...,https://m.media-amazon.com/images/M/MV5BMTc0Nz...,https://www.youtube.com/watch?v=5kyF2vy63r0,YouTube
4,Only a Mother,Drama,"Social Issue Dramas,Dramas,Movies Based on Boo...",Swedish,Movie,8.3,"Lithuania,Poland,France,Italy,Spain,Greece,Bel...",1-2 hour,Alf Sj√∂berg,Ivar Lo-Johansson,...,2021-03-03,NaN,https://www.netflix.com/watch/81382068,https://www.imdb.com/title/tt0041155,An unhappily married farm worker struggling to...,88.0,https://occ-0-2851-41.1.nflxso.net/dnm/api/v6/...,https://m.media-amazon.com/images/M/MV5BMjVmMz...,https://www.youtube.com/watch?v=H0itWKFwMpQ,YouTube
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9420,13 Going on 30,"Comedy, Fantasy, Romance","Romantic Comedies,Comedies,Romantic Films,Roma...","English, Portuguese",Movie,3.1,"Hungary,Lithuania,Romania,United Kingdom,Belgi...",1-2 hour,Gary Winick,"Josh Goldsmith, Cathy Yuspa",...,2015-04-14,"Revolution Studios, Thirteen Productions LLC",https://www.netflix.com/watch/60034573,https://www.imdb.com/title/tt0337563,When a geeky teens birthday party goes awry an...,167842.0,https://occ-0-2851-38.1.nflxso.net/dnm/api/v6/...,https://images-na.ssl-images-amazon.com/images...,https://www.youtube.com/watch?v=SApIKVq1iJQ,YouTube
9421,LIFE 2.0,Documentary,"Social & Cultural Documentaries,Biographical D...",English,Movie,8.2,"Hungary,Lithuania,India,Australia,United Kingd...",1-2 hour,Jason Spingarn-Koff,NaN,...,2015-04-14,NaN,https://www.netflix.com/watch/70129457,https://www.imdb.com/title/tt1518809,Computer users across the globe log onto the v...,878.0,https://occ-0-2851-38.1.nflxso.net/dnm/api/v6/...,https://images-na.ssl-images-amazon.com/images...,https://www.youtube.com/watch?v=2TY-O5Dc8oA,YouTube
9422,Brand New Day,"Documentary, Music","Australian Comedies,Romantic Comedies,Australi...",English,Movie,8.6,Australia,1-2 hour,Amos Gitai,NaN,...,2015-04-14,NaN,https://www.netflix.com/watch/70125340,NaN,In an idyllic port town on Australias west coa...,14.0,http://cdn1.nflximg.net/images/5543/12045543.jpg,NaN,https://www.youtube.com/watch?v=RnGRdaX594k,YouTube
9423,Daniel Arends: Blessuretijd,Comedy,"Stand-up Comedy,International Movies,Comedies",Dutch,Movie,8.8,Belgium,1-2 hour,Doesjka van Hoogdalem,Dani√´l Arends,...,2015-04-14,NaN,https://www.netflix.com/watch/70281233,NaN,"In his third show, Dani√´l Arends argues that g...",174.0,http://occ-0-768-769.1.nflxso.net/dnm/api/v6/e...,NaN,https://www.youtube.com/watch?v=vVCEm1G8Zss,YouTube
9424,DreamWorks Happy Holidays from Madagascar,"Animation, Comedy, Family","TV Comedies,Kids TV,Animal Tales,TV Cartoons,T...",English,Series,8.4,"Belgium,Switzerland,United States,Germany,Unit...",< 30 minutes,NaN,NaN,...,2015-04-14,NaN,https://www.netflix.com/watch/70259784,NaN,Madagascar goes wild with holiday spirit in th...,71.0,https://occ-0-2773-2774.1.nflxso.net/dnm/api/v...,NaN,https://www.youtube.com/watch?v=hOwDHUAQR9k,NaN

In [5]:
df.columns

Index(['Title', 'Genre', 'Tags', 'Languages', 'Series or Movie',
       'Hidden Gem Score', 'Country Availability', 'Runtime', 'Director',
       'Writer', 'Actors', 'View Rating', 'IMDb Score',
       'Rotten Tomatoes Score', 'Metacritic Score', 'Awards Received',
       'Awards Nominated For', 'Boxoffice', 'Release Date',
       'Netflix Release Date', 'Production House', 'Netflix Link', 'IMDb Link',
       'Summary', 'IMDb Votes', 'Image', 'Poster', 'TMDb Trailer',
       'Trailer Site'],
      dtype='object')

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9425 entries, 0 to 9424
Data columns (total 29 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Title                  9425 non-null   object
 1   Genre                  9400 non-null   object
 2   Tags                   9389 non-null   object
 3   Languages              9266 non-null   object
 4   Series or Movie        9425 non-null   object
 5   Hidden Gem Score       9415 non-null   float64
 6   Country Availability   9414 non-null   object
 7   Runtime                9424 non-null   object
 8   Director               7120 non-null   object
 9   Writer                 7615 non-null   object
 10  Actors                 9314 non-null   object
 11  View Rating            6827 non-null   object
 12  IMDb Score             9417 non-null   float64
 13  Rotten Tomatoes Score  5445 non-null   float64
 14  Metacritic Score       4082 non-null   float64
 15  Awards Received        5226 non-null   float64
 16  Awards Nominated For   6376 non-null   float64
 17  Boxoffice              3754 non-null   float64
 18  Release Date           9217 non-null   datetime64[ns]
 19  Netflix Release Date   9425 non-null   datetime64[ns]
 20  Production House       4393 non-null   object
 21  Netflix Link           9425 non-null   object
 22  IMDb Link              9101 non-null   object
 23  Summary                9420 non-null   object
 24  IMDb Votes             9415 non-null   float64
 25  Image                  9425 non-null   object
 26  Poster                 8487 non-null   object
 27  TMDb Trailer           9425 non-null   object
 28  Trailer Site           9424 non-null   object
dtypes: datetime64[ns](2), float64(8), object(19)
memory usage: 2.1+ MB

In [7]:
df.isnull().sum()

Title                       0
Genre                      25
Tags                       36
Languages                 159
Series or Movie             0
Hidden Gem Score           10
Country Availability       11
Runtime                     1
Director                 2305
Writer                   1810
Actors                    111
View Rating              2598
IMDb Score                  8
Rotten Tomatoes Score    3980
Metacritic Score         5343
Awards Received          4199
Awards Nominated For     3049
Boxoffice                5671
Release Date              208
Netflix Release Date        0
Production House         5032
Netflix Link                0
IMDb Link                 324
Summary                     5
IMDb Votes                 10
Image                       0
Poster                    938
TMDb Trailer                0
Trailer Site                1
dtype: int64

In [8]:
df.describe()

,Hidden Gem Score,IMDb Score,Rotten Tomatoes Score,Metacritic Score,Awards Received,Awards Nominated For,Boxoffice,IMDb Votes
count,9415.000000,9417.000000,5445.000000,4082.000000,5226.000000,6376.000000,3.754000e+03,9.415000e+03
mean,5.540733,6.955517,64.691276,58.113425,9.735936,16.035602,4.845788e+07,6.014725e+04
std,2.447462,0.899681,25.269466,17.143187,19.524116,32.209094,7.243625e+07,1.463837e+05
min,0.600000,1.600000,0.000000,6.000000,1.000000,1.000000,7.200000e+01,5.000000e+00
25%,3.400000,6.500000,49.000000,46.000000,1.250000,2.000000,1.243910e+06,9.695000e+02
50%,5.300000,7.000000,70.000000,59.000000,4.000000,6.000000,2.250466e+07,6.602000e+03
75%,8.100000,7.500000,85.000000,71.000000,9.000000,15.000000,6.425437e+07,5.098700e+04
max,9.800000,9.700000,100.000000,100.000000,300.000000,386.000000,6.593639e+08,2.354197e+06

In [13]:
df=df.drop(columns=['Netflix Link','IMDb Link','Summary','Image','Poster','TMDb Trailer','Trailer Site'])

In [14]:
df.columns

Index(['Title', 'Genre', 'Tags', 'Languages', 'Series or Movie',
       'Hidden Gem Score', 'Country Availability', 'Runtime', 'Director',
       'Writer', 'Actors', 'View Rating', 'IMDb Score',
       'Rotten Tomatoes Score', 'Metacritic Score', 'Awards Received',
       'Awards Nominated For', 'Boxoffice', 'Release Date',
       'Netflix Release Date', 'Production House', 'IMDb Votes'],
      dtype='object')

In [17]:
max_ratings=df['IMDb Score'].max()

In [19]:
df.loc[df['IMDb Score']==max_ratings]

,Title,Genre,Tags,Languages,Series or Movie,Hidden Gem Score,Country Availability,Runtime,Director,Writer,...,IMDb Score,Rotten Tomatoes Score,Metacritic Score,Awards Received,Awards Nominated For,Boxoffice,Release Date,Netflix Release Date,Production House,IMDb Votes
187,No Festival,"Documentary, Music","Music & Musicals,Music & Concert Documentaries...",Romanian,Movie,9.8,Romania,1-2 hour,Dorin Marcu,Andy Daniluc,...,9.7,NaN,NaN,NaN,NaN,NaN,2020-07-15,2021-01-24,NaN,49.0

In [21]:
hindi_df=df.loc[df['Languages']=='Hindi']

In [29]:
a=hindi_df[['Title','IMDb Score']].groupby(['Title','IMDb Score']).size().reset_index()

In [30]:
a

                        Title  IMDb Score  0
0                 A Wednesday         8.1  1
1    ABCD: Any Body Can Dance         6.3  1
2                    AK vs AK         7.0  1
3                       Aamir         7.7  1
4                   Agneepath         7.7  1
..                        ...         ... ..
177      Welcome to Sajjanpur         6.9  1
178            Well Done Abba         7.3  1
179                Yeh Ballet         7.6  1
180                      Zero         5.4  1
181      ‚Äã‚ÄãKuch Bheege Alfaaz         7.5  1

[182 rows x 3 columns]

In [36]:
a.sort_values(by='IMDb Score',ascending=False).head(10)

                             Title  IMDb Score  0
145               Regiment Diaries         9.1  1
140  Raja Rasoi Aur Anya Kahaniyan         9.0  1
33                 College Romance         8.9  1
24                    Black Friday         8.5  1
161               Taare Zameen Par         8.4  1
36                   Dharmakshetra         8.2  1
143                Rang De Basanti         8.2  1
122               Paan Singh Tomar         8.2  1
12                      Article 15         8.2  1
64      Gangs of Wasseypur: Part 1         8.2  1

In [37]:
a.value_counts()

Title                        IMDb Score  0
A Wednesday                  8.1         1    1
Mighty Little Bheem: Diwali  7.0         1    1
Mom                          7.3         1    1
Mumbai Meri Jaan             7.7         1    1
Muzaffarnagar Baaqi Hai      6.9         1    1
                                             ..
Gabbar Is Back               7.1         1    1
Gangaajal                    7.8         1    1
Gangs of Wasseypur: Part 1   8.2         1    1
Gangs of Wasseypur: Part 2   8.2         1    1
‚Äã‚ÄãKuch Bheege Alfaaz         7.5         1    1
Length: 182, dtype: int64

In [48]:
indian_netflix=df.loc[df['Country Availability']=='India']

In [53]:
b=indian_netflix[['Title','IMDb Score']].groupby(['Title','IMDb Score']).size().reset_index()

In [55]:
top10_indian=b.sort_values(by='IMDb Score',ascending=False).head(10)

In [56]:
top10_indian

                         Title  IMDb Score  0
26  Gangs of Wasseypur: Part 2         8.2  1
39                      Masaan         8.2  1
25  Gangs of Wasseypur: Part 1         8.2  1
38    Manjhi: The Mountain Man         8.0  1
57                The Lunchbox         7.8  1
12                      Blippi         7.8  1
6              Ask the Sexpert         7.6  1
40         Matangi/Maya/M.I.A.         7.6  1
34                    Loveless         7.6  1
54             The Kite Runner         7.6  1

In [43]:
best_rating=indian_netflix['IMDb Score'].max()

In [44]:
best_rating

8.2

In [46]:
top_movie=indian_netflix.loc[indian_netflix['IMDb Score']==best_rating]

In [47]:
top_movie

,Title,Genre,Tags,Languages,Series or Movie,Hidden Gem Score,Country Availability,Runtime,Director,Writer,...,IMDb Score,Rotten Tomatoes Score,Metacritic Score,Awards Received,Awards Nominated For,Boxoffice,Release Date,Netflix Release Date,Production House,IMDb Votes
5672,Masaan,Drama,"International Dramas,International Movies,Dramas",Hindi,Movie,4.3,India,1-2 hour,Neeraj Ghaywan,"Mirza Ghalib, Brij Narayan Chakbast, Akbar All...",...,8.2,92.0,NaN,22.0,8.0,NaN,2015-06-24,2016-12-13,NaN,23841.0
6446,Gangs of Wasseypur: Part 2,"Action, Comedy, Crime, Drama, Thriller","Dramas,International Action & Adventure,Epics,...",Hindi,Movie,4.5,India,> 2 hrs,Anurag Kashyap,"Akhilesh Jaiswal, Anurag Kashyap, Zeishan Quad...",...,8.2,97.0,89.0,17.0,45.0,NaN,2012-06-22,2016-01-21,NaN,82342.0
6447,Gangs of Wasseypur: Part 1,"Action, Comedy, Crime, Drama, Thriller","Action & Adventure,Crime Action & Adventure,In...",Hindi,Movie,4.5,India,> 2 hrs,Anurag Kashyap,"Akhilesh Jaiswal, Anurag Kashyap, Zeishan Quad...",...,8.2,97.0,89.0,17.0,45.0,NaN,2012-06-22,2016-01-21,NaN,82342.0